# Generated by Django 5.2.5 on 2025-09-03 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Department name')),
                ('slug', models.SlugField(help_text='URL-friendly unique identifier', max_length=160, unique=True, verbose_name='Slug')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='departments/icons/', verbose_name='Icon')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('priority', models.IntegerField(default=0, help_text='Lower number appears first', verbose_name='Priority')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ('priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='HealthPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='Package name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(help_text='URL-friendly unique identifier', max_length=190, unique=True, verbose_name='Slug')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='health_packages/images/', verbose_name='Image')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('priority', models.IntegerField(default=0, help_text='Lower number appears first', verbose_name='Priority')),
            ],
            options={
                'verbose_name': 'Health Package',
                'verbose_name_plural': 'Health Packages',
                'ordering': ('priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Doctor name')),
                ('slug', models.SlugField(help_text='URL-friendly unique identifier', max_length=160, unique=True, verbose_name='Slug')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.TextField(blank=True, verbose_name='Description / Bio')),
                ('priority', models.IntegerField(default=0, help_text='Lower number appears first', verbose_name='Priority')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='mainapp.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ('priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DepartmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Service name')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier (optional)', max_length=160, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('priority', models.IntegerField(default=0, help_text='Lower number appears first', verbose_name='Priority')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='mainapp.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Department Service',
                'verbose_name_plural': 'Department Services',
                'ordering': ('priority', 'name'),
                'constraints': [models.UniqueConstraint(fields=('department', 'name'), name='uniq_service_name_per_department')],
            },
        ),
    ]
