# Generated by Django 5.2.5 on 2025-09-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_blogcategory_blogtag_gallery_service_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='email1',
            field=models.CharField(blank=True, default='info@hopehospital.com.np', max_length=30, verbose_name='Primary Email'),
        ),
        migrations.AddField(
            model_name='settings',
            name='email2',
            field=models.CharField(blank=True, default='info@hopehospital.com.np', max_length=30, verbose_name='Secondary Email'),
        ),
        migrations.AddField(
            model_name='settings',
            name='org_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='map_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Map link <iframe>'),
        ),
    ]
