# Generated by Django 5.2.5 on 2025-09-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_settings_email1_settings_email2_settings_org_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='map_link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Google Map link <iframe>'),
        ),
    ]
