# Generated by Django 5.2.5 on 2025-09-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services/icon/', verbose_name='Logo'),
        ),
    ]
