# Generated by Django 5.2.5 on 2025-09-04 05:17

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content (Markdown/HTML)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='internal_notes',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Internal notes'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='message',
            field=tinymce.models.HTMLField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=tinymce.models.HTMLField(help_text='HTML allowed', verbose_name='Content (HTML)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='departmentservice',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Description / Bio'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='healthpackage',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='message',
            field=tinymce.models.HTMLField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='service',
            name='desc',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='address',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='teamdepartment',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='videoalbum',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Description'),
        ),
    ]
