# Generated by Django 5.2.5 on 2025-09-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_blogcategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='position',
            field=models.CharField(default='Doctor', max_length=100),
        ),
    ]
