# Generated by Django 5.2.5 on 2025-09-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_doctor_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide1_text', models.CharField(default='Welcome to Slide 1', max_length=255)),
                ('slide2_text', models.CharField(default='Welcome to Slide 2', max_length=255)),
                ('slide3_text', models.CharField(default='Welcome to Slide 3', max_length=255)),
                ('slide1_image', models.ImageField(blank=True, null=True, upload_to='slides/')),
                ('slide2_image', models.ImageField(blank=True, null=True, upload_to='slides/')),
                ('slide3_image', models.ImageField(blank=True, null=True, upload_to='slides/')),
                ('slide1_desc', models.TextField(default='Slide 1 description here...')),
                ('slide2_desc', models.TextField(default='Slide 2 description here...')),
                ('slide3_desc', models.TextField(default='Slide 3 description here...')),
                ('md_message', models.TextField(default='Message from the Managing Director...')),
                ('md_pic', models.ImageField(blank=True, null=True, upload_to='directors/')),
                ('chairman_message', models.TextField(default='Message from the Chairman...')),
                ('chairman_pic', models.ImageField(blank=True, null=True, upload_to='chairman/')),
            ],
            options={
                'verbose_name': 'Website Content',
                'verbose_name_plural': 'Website Content',
            },
        ),
    ]
