# Generated by Django 5.2.5 on 2025-09-04 08:22

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_websitecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecontent',
            name='chairman_message',
            field=tinymce.models.HTMLField(default='Message from the Chairman...'),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='md_message',
            field=tinymce.models.HTMLField(default='Message from the Managing Director...'),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='slide1_desc',
            field=tinymce.models.HTMLField(default='Slide 1 description here...'),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='slide2_desc',
            field=tinymce.models.HTMLField(default='Slide 2 description here...'),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='slide3_desc',
            field=tinymce.models.HTMLField(default='Slide 3 description here...'),
        ),
    ]
