# Generated by Django 5.2.5 on 2025-09-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_websitecontent_chairman_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
    ]
