# Generated by Django 5.2.5 on 2025-09-03 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0002_blogcategory_blogtag_gallery_service_settings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('patient_name', models.CharField(max_length=150, verbose_name='Patient name')),
                ('patient_phone', models.CharField(max_length=30, verbose_name='Patient phone')),
                ('patient_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Patient email')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Reason (short)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', max_length=12, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='mainapp.doctor', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ('-appointment_date', 'start_time'),
                'indexes': [models.Index(fields=['doctor', 'appointment_date', 'start_time'], name='appointment_doctor__4561f2_idx')],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'appointment_date', 'start_time'), name='uniq_doctor_date_start')],
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], verbose_name='Day of week')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('slot_minutes', models.PositiveSmallIntegerField(default=15, verbose_name='Slot duration (min)')),
                ('max_patients_per_slot', models.PositiveSmallIntegerField(default=1, verbose_name='Max patients per slot')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='Effective from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Effective to')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('priority', models.IntegerField(default=0, help_text='Lower number appears first', verbose_name='Priority')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='mainapp.doctor', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Doctor Availability',
                'verbose_name_plural': 'Doctor Availabilities',
                'ordering': ('day_of_week', 'start_time'),
                'constraints': [models.UniqueConstraint(fields=('doctor', 'day_of_week', 'start_time', 'end_time'), name='uniq_doctor_day_time_block')],
            },
        ),
    ]
