"""
Django settings for hopehospital project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4w^+4!sj5h^0a*@jgn@f)i6l3ib^x3i6damu+(r1u40s55v1$0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    "unfold.contrib.constance",  # optional, if django-constance package is used
     'tinymce',
    'appointment',
    'jobboard',
    'mainapp',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',

     
]
 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
     "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hopehospital.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'mainapp.context_processors.global_site_context'
            ],
        },
    },
]

WSGI_APPLICATION = 'hopehospital.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'  # URL prefix
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Your project-level static folder
]
STATIC_ROOT = BASE_DIR / "staticfiles"  # For collectstatic in production

# Media files (User uploads)
MEDIA_URL = '/media/'  # URL prefix
MEDIA_ROOT = BASE_DIR / "media"  # Folder to store uploaded files


# settings.py (or wherever you define UNFOLD)
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "Hope Hospital Website Admin",
    "SITE_HEADER": "Hope Hospital Admin",
    "SITE_SUBHEADER": "Powerd by Cortifox",
    "COLORS": {
        "base": {
            "50": "249, 250, 251",
            "100": "243, 244, 246",
            "200": "229, 231, 235",
            "300": "209, 213, 219",
            "400": "156, 163, 175",
            "500": "107, 114, 128",
            "600": "75, 85, 99",
            "700": "55, 65, 81",
            "800": "31, 41, 55",
            "900": "17, 24, 39",
            "950": "3, 7, 18",
        },
        "primary": {
            "50": "239, 246, 255",
            "100": "219, 234, 254",
            "200": "191, 219, 254",
            "300": "147, 197, 253",
            "400": "96, 165, 250",
            "500": "59, 130, 246",
            "600": "37, 99, 235",
            "700": "29, 78, 216",
            "800": "30, 64, 175",
            "900": "30, 58, 138",
            "950": "23, 37, 84",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "command_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Main Site"),
                "icon": "public",
                "link": reverse_lazy("admin:index"),
                "collapsible": True,
                "permission": lambda request: request.user.is_authenticated,
                "items": [
                    {
                        "title": _("Departments"),
                        "icon": "apartment",
                        "link": reverse_lazy("admin:mainapp_department_changelist"),
                    },
                    {
                        "title": _("Department Services"),
                        "icon": "handyman",
                        "link": reverse_lazy("admin:mainapp_departmentservice_changelist"),
                    },
                    {
                        "title": _("Doctors"),
                        "icon": "vaccines",
                        "link": reverse_lazy("admin:mainapp_doctor_changelist"),
                    },
                    {
                        "title": _("Health Packages"),
                        "icon": "medical_services",
                        "link": reverse_lazy("admin:mainapp_healthpackage_changelist"),
                    },
                    {
                        "title": _("Services"),
                        "icon": "home_repair_service",
                        "link": reverse_lazy("admin:mainapp_service_changelist"),
                    },
                ],
            },

            {
                "title": _("Team"),
                "icon": "groups_3",
                "link": reverse_lazy("admin:index"),
                "collapsible": True,
                "permission": lambda request: request.user.is_authenticated,
                "items": [
                    {
                        "title": _("Team Departments"),
                        "icon": "diversity_3",
                        "link": reverse_lazy("admin:mainapp_teamdepartment_changelist"),
                    },
                    {
                        "title": _("Team Members"),
                        "icon": "badge",
                        "link": reverse_lazy("admin:mainapp_teammember_changelist"),
                    },
                ],
            },

            {
                "title": _("Media"),
                "icon": "collections",
                "link": reverse_lazy("admin:index"),
                "collapsible": True,
                "permission": lambda request: request.user.is_authenticated,
                "items": [
                    {
                        "title": _("Galleries"),
                        "icon": "photo_library",
                        "link": reverse_lazy("admin:mainapp_gallery_changelist"),
                    },
                    {
                        "title": _("Gallery Pictures"),
                        "icon": "image",
                        "link": reverse_lazy("admin:mainapp_gallerypic_changelist"),
                    },
                    {
                        "title": _("Video Albums"),
                        "icon": "video_library",
                        "link": reverse_lazy("admin:mainapp_videoalbum_changelist"),
                    },
                    {
                        "title": _("Videos"),
                        "icon": "videocam",
                        "link": reverse_lazy("admin:mainapp_video_changelist"),
                    },
                ],
            },

            {
                "title": _("News & Content"),
                "icon": "newspaper",
                "link": reverse_lazy("admin:index"),
                "collapsible": True,
                "permission": lambda request: request.user.is_authenticated,
                "items": [
                    {
                        "title": _("Latest News"),
                        "icon": "article",
                        "link": reverse_lazy("admin:mainapp_latestnews_changelist"),
                    },
                    {
                        "title": _("Notices"),
                        "icon": "campaign",
                        "link": reverse_lazy("admin:mainapp_notice_changelist"),
                    },
                    {
                        "title": _("Blog Categories"),
                        "icon": "category",
                        "link": reverse_lazy("admin:mainapp_blogcategory_changelist"),
                    },
                    {
                        "title": _("Blog Tags"),
                        "icon": "sell",
                        "link": reverse_lazy("admin:mainapp_blogtag_changelist"),
                    },
                    {
                        "title": _("Blog Posts"),
                        "icon": "rss_feed",
                        "link": reverse_lazy("admin:mainapp_blogpost_changelist"),
                    },
                    {
                        "title": _("Pages / Content"),
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:mainapp_content_changelist"),
                    },
                ],
            },

            {
                "title": _("Contact & Engagement"),
                "icon": "mail",
                "link": reverse_lazy("admin:index"),
                "collapsible": True,
                "permission": lambda request: request.user.is_authenticated,
                "items": [
                    {
                        "title": _("Contact Submissions"),
                        "icon": "mark_email_unread",
                        "link": reverse_lazy("admin:mainapp_contactsubmission_changelist"),
                    },
                ],
            },

            # -------------------------
            # Job Board (jobboard app)
            # -------------------------
            {
                "title": _("Job Board"),
                "icon": "work",
                "link": reverse_lazy("admin:index"),
                "collapsible": True,
                "permission": lambda request: request.user.is_authenticated,
                "items": [
                    {
                                "title": _("Departments"),
                                "icon": "apartment",
                                "link": reverse_lazy("admin:jobboard_department_changelist"),
                            },
                            {
                                "title": _("Locations"),
                                "icon": "location_on",
                                "link": reverse_lazy("admin:jobboard_location_changelist"),
                            },
                            {
                                "title": _("Specialties"),
                                "icon": "stethoscope",
                                "link": reverse_lazy("admin:jobboard_specialty_changelist"),
                            },
                            {
                                "title": _("Credentials / Licenses"),
                                "icon": "badge",
                                "link": reverse_lazy("admin:jobboard_credential_changelist"),
                            },
                    {
                        "title": _("Job Postings"),
                        "icon": "campaign",
                        "link": reverse_lazy("admin:jobboard_jobposting_changelist"),
                        "items": [
                            {
                                "title": _("All Jobs"),
                                "icon": "work_outline",
                                "link": reverse_lazy("admin:jobboard_jobposting_changelist"),
                            },
                            {
                                "title": _("Screening Questions"),
                                "icon": "quiz",
                                "link": reverse_lazy("admin:jobboard_screeningquestion_changelist"),
                            },
                        ],
                    },
                    {
                        "title": _("Candidates"),
                        "icon": "person_search",
                        "link": reverse_lazy("admin:jobboard_candidate_changelist"),
                        "items": [
                            {
                                "title": _("Profiles"),
                                "icon": "person",
                                "link": reverse_lazy("admin:jobboard_candidate_changelist"),
                            },
                            {
                                "title": _("Applications"),
                                "icon": "how_to_reg",
                                "link": reverse_lazy("admin:jobboard_application_changelist"),
                            },
                            {
                                "title": _("Stage Changes"),
                                "icon": "timeline",
                                "link": reverse_lazy("admin:jobboard_applicationstatushistory_changelist"),
                            },
                        ],
                    },
                     {
                                "title": _("Interviews"),
                                "icon": "calendar_month",
                                "link": reverse_lazy("admin:jobboard_interview_changelist"),
                            },
                            {
                                "title": _("Interview Feedback"),
                                "icon": "rate_review",
                                "link": reverse_lazy("admin:jobboard_interviewfeedback_changelist"),
                            },
                            {
                                "title": _("Offers"),
                                "icon": "request_quote",
                                "link": reverse_lazy("admin:jobboard_offer_changelist"),
                            },
                    {
                        "title": _("Onboarding"),
                        "icon": "assignment_turned_in",
                        "link": reverse_lazy("admin:jobboard_onboardingtask_changelist"),
                    },
                     
                ],
            },

            {
                "title": _("Administration"),
                "icon": "settings",
                "link": reverse_lazy("admin:index"),
                "collapsible": True,
                "permission": lambda request: request.user.is_superuser,
                "items": [
                    {
                        "title": _("Site Settings"),
                        "icon": "tune",
                        "link": reverse_lazy("admin:mainapp_settings_changelist"),
                    },
                    {
                        "title": _("Users"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group_work",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# SMTP settings
EMAIL_HOST = "mail.vedanica.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Credentials
EMAIL_HOST_USER = "info@vedanica.com"
EMAIL_HOST_PASSWORD = "Balkot11@"  # NOT your Gmail password

# Default from
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


 