# Generated by Django 5.2.5 on 2025-09-05 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('from_stage', models.CharField(choices=[('APPLIED', 'Applied'), ('SCREENING', 'Screening'), ('ASSESSMENT', 'Assessment'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], max_length=15, verbose_name='from stage')),
                ('to_stage', models.CharField(choices=[('APPLIED', 'Applied'), ('SCREENING', 'Screening'), ('ASSESSMENT', 'Assessment'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], max_length=15, verbose_name='to stage')),
                ('note', models.TextField(blank=True, verbose_name='note')),
            ],
            options={
                'verbose_name': 'Application Stage Change',
                'verbose_name_plural': 'Application Stage Changes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.CheckConstraint(condition=models.Q(('salary_min__isnull', True), ('salary_max__isnull', True), ('salary_min__lte', models.F('salary_max')), _connector='OR'), name='job_salary_min_lte_max_or_null'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.CheckConstraint(condition=models.Q(('experience_max_years', 0), ('experience_min_years__lte', models.F('experience_max_years')), _connector='OR'), name='job_exp_min_lte_max_or_zero'),
        ),
        migrations.AddField(
            model_name='applicationstatushistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='jobboard.application', verbose_name='application'),
        ),
        migrations.AddField(
            model_name='applicationstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_stage_changes', to=settings.AUTH_USER_MODEL, verbose_name='changed by'),
        ),
    ]
